# Generated by Django 3.2.23 on 2024-06-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
