import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from cheesystoreshop.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    # Unique order number generated by UUID
    order_number = models.CharField(max_length=32, null=False, editable=False)
    # Optional link to a user profile
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders'
    )
    # Customer information fields
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    # Address fields, using django-countries for the country field
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    # Order timestamps
    date = models.DateTimeField(auto_now_add=True)
    # Financial fields for the order
    delivery_cost = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        default=0
    )
    order_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0
    )
    grand_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0
    )
    # Store the original bag and Stripe payment ID
    original_bag = models.TextField(
        null=False,
        blank=False,
        default=''
    )
    stripe_pid = models.CharField(
        max_length=254,
        null=False,
        blank=False,
        default=''
    )

    def _generate_order_number(self):
        # Generate a random, unique order number using UUID
        return uuid.uuid4().hex.upper()

    def update_total(self):
        # Update order totals and save

        total_sum = self.lineitems.aggregate(
            total=Sum('lineitem_total')
        )['total']

        self.order_total = total_sum if total_sum is not None else 0

        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost =\
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        # Ensure an order number is generated for new orders
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        # String representation of the Order model
        return self.order_number


class OrderLineItem(models.Model):
    # Link to the Order and Product models
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='lineitems'
    )
    product = models.ForeignKey(
        Product,
        null=False,
        blank=False,
        on_delete=models.CASCADE
    )
    # Quantity of the product in the order
    quantity = models.IntegerField(null=False, blank=False, default=0)
    # Automatically calculated total for the line item
    lineitem_total = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        editable=False
    )

    def save(self, *args, **kwargs):
        # Calculate the line item total on save
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        # String representation of the OrderLineItem model
        return f'SKU {self.product.sku} on order {self.order.order_number}'
